[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20", "tesseract", "poppler_utils"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache", 
    "php artisan view:cache"
]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/" 